const FIVE_MINUTES_IN_SECONDS = 300;
const SIXTY_MINUTES_IN_SECONDS = 3600;
const THIRTY_DAYS = '30 days';
const FIFTY_MINUTES = '15m';

module.exports = {
  FIVE_MINUTES_IN_SECONDS,
  SIXTY_MINUTES_IN_SECONDS,
  THIRTY_DAYS,
  FIFTY_MINUTES,
};
